### ISSUE TITLE
error while trying to run in kubernetes - docker exec format error

### ISSUE THREAD

**Issue by Gordonfreeman882** [ertagh/teamspeak3-server-arm#36]
Hey man,

thanks for the provided files. 
I'm trying to run your container in kubernetes on a PI cm4 which should be ARMv8.

I'm using your image with 'latest' tag since it supports ARMv8. 
When starting the following error appears in the logs of my pod:
```
Version 3.13.7 installed succesfully!
Starting TeamSpeak 3 Server ..
Starting TeamSpeak 3 Server ..
/teamspeak/ts3server_minimal_runscript.sh: 20: /teamspeak/ts3server_minimal_runscript.sh: ./ts3server: Exec format error
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
I'm not quite sure where to look for the error since it looks like 'exec format error' can mean a missing #!/bin/bash or an image on unsupported architecture.

Any ideas?

Thanks!

**Comment by ertagh** [comment]
Well that's odd...
I just tested it on my RPi 3b+ and there is no problem.
May you provide what envs you set?

Also just wanna mention it:
You may wanna switch to the `latest-box` tag. Better performance and it even runs the actual x64 binaries on ARMv8.

**Comment by Gordonfreeman882** [comment]
Hey,
i've set the following envs using `latest-box` image:
```
env:
            - name: TIME_ZONE
              value: Europe/Berlin
            - name: DIST_UPDATE
              value: "0"
            - name: TS_UPDATE
              value: "0"
            - name: TS_UPDATE_BACKUP
              value: "1"
            - name: UID
              value: "1000"
            - name: GID
              value: "1000"
            - name: INIFILE
              value: "0"
            - name: DEBUG
              value: "0"
            - name: TS_ARCHITECTURE
              value: x86_64
            - name: SYSTEM_ARCHITECTURE
              value: x86_64
            - name: TS3SERVER_LICENSE
              value: accept
            - name: LANG
              value: en_US.UTF-8
```
