### ISSUE TITLE
TeamSpeak server could not validate your myTeamSpeak ID

### ISSUE THREAD

**Issue by tio-27** [ertagh/teamspeak3-server-arm#48]
Hello, i am running the Container On an RPI5 with the latest RaspberryPi OS lit 64bit, latest Docker Version.

My Composefile looks like this:

```
services:
  teamspeak3-server:
    container_name: TeamSpeak3_Server
    environment:
      - TS_UPDATE=1
      - TIME_ZONE=Europe/Berlin
    ports:
      - 9987:9987/udp
      - 10011:10011/tcp
      - 30033:30033/tcp
    volumes:
      - /docker/teamspeak3:/teamspeak/save/"
    image: ertagh/teamspeak3-server:latest-box
    restart: unless-stopped
networks: {}

```

Like the Titel sad i get following error when connection to the server:

```
￼<17:10:09> Welcome to TeamSpeak, check [www.teamspeak.com](http://www.teamspeak.com/) for latest information
￼<17:10:09> Connected to Server: ["TeamSpeak ]I[ Server"](channelid://0)
￼<17:10:10> The TeamSpeak server could not validate your myTeamSpeak ID. Some myTeamSpeak related services are not available.
￼<17:10:10> Reconnecting might solve the issue.
￼<17:10:10> myTeamSpeak ID is invalid
```

I checkt the internet connection of the container:

```
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=57 time=9.74 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=57 time=13.8 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=57 time=10.4 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=57 time=10.2 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=57 time=10.2 ms

--- 1.1.1.1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4007ms
rtt min/avg/max/mdev = 9.740/10.886/13.838/1.491 ms

PING myteamspeak.com (104.18.26.233) 56(84) bytes of data.
64 bytes from 104.18.26.233 (104.18.26.233): icmp_seq=1 ttl=57 time=13.5 ms
64 bytes from 104.18.26.233 (104.18.26.233): icmp_seq=2 ttl=57 time=9.90 ms
64 bytes from 104.18.26.233 (104.18.26.233): icmp_seq=3 ttl=57 time=9.96 ms
64 bytes from 104.18.26.233 (104.18.26.233): icmp_seq=4 ttl=57 time=10.0 ms
64 bytes from 104.18.26.233 (104.18.26.233): icmp_seq=5 ttl=57 time=12.9 ms
64 bytes from 104.18.26.233 (104.18.26.233): icmp_seq=6 ttl=57 time=11.9 ms

--- myteamspeak.com ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5007ms
rtt min/avg/max/mdev = 9.900/11.349/13.462/1.470 ms
```
So the connection is not the problem.
Its not a big issue because the Server works as far as i can tell. But its still an annoyance. 
Am i missing something or is it a bug?
